-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.favoritedrecipes
(
    id bigserial NOT NULL,
    user_id integer NOT NULL,
    recipe_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    unfavorited boolean NOT NULL,
    CONSTRAINT favoritedrecipes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ingredients
(
    id bigserial NOT NULL,
    user_id integer NOT NULL,
    ingredient_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    category character varying(50) COLLATE pg_catalog."default" NOT NULL,
    added_date date,
    expiration_date date,
    amount character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ingredients_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ingredientslist
(
    id bigserial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ingredientslist_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ingredientslist_users
(
    ingredientslist_id integer NOT NULL,
    users_id bigserial NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    auth0_id character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_auth0_id_key UNIQUE (auth0_id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.favoritedrecipes
    ADD CONSTRAINT favoritedrecipes_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.ingredients
    ADD CONSTRAINT ingredients_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.ingredientslist_users
    ADD CONSTRAINT ingredientslist_users_ingredientslist_id_fkey FOREIGN KEY (ingredientslist_id)
    REFERENCES public.ingredientslist (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ingredientslist_users
    ADD CONSTRAINT ingredientslist_users_users_id_fkey FOREIGN KEY (users_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;